@startuml
hide empty description

[*] -> LoadedMapState
LoadedMapState : A map has been loaded into the software.
FileChooserState : A file browser pops up
FileChoosedState : A file has been selected

LoadedMapState -> FileChooserState : leftClick [Save requests]
FileChooserState --> FileChoosedState : Fill filename field
FileChooserState --> LoadedMapState : leftClick [Cancel]
FileChoosedState --> LoadedMapState : leftClick [Save]
@enduml